name: LightNVR
version: "0.1.2"
slug: lightnvr
description: Lightweight Network Video Recorder (NVR)
url: https://github.com/opensensor/lightnvr
arch:
  - amd64
  - aarch64
  - armv7
build_from:
  amd64: ghcr.io/opensensor/lightnvr:latest
  aarch64: ghcr.io/opensensor/lightnvr:latest
  armv7: ghcr.io/opensensor/lightnvr:latest
startup: services
boot: auto
init: false
host_network: true
map:
  - addon_config:rw
  - media:rw
options: {}
schema: {}
